### ISSUE TITLE
AppRegistryNotReady on Hawthorn.2

### ISSUE THREAD

**Issue by eazaika** [zimka/npoed_multiproctoring#1]
Hi,
i had try it on the edx hawthorn.2. Installed npoed_multiproctoring by a pip, added to lms/envs/aws

`INSTALLED_APPS += ("open_edx_api_extension", "npoed_multiproctoring")`
When i do
`
python manage.py lms makemigrations npoed_multiproctoring --settings=aws
`
logs tells about error
```
Traceback (most recent call last):
  File "manage.py", line 118, in <module>
    startup.run()
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 19, in run
    django.setup()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/venvs/edxapp/src/npoed-multiproctoring/npoed_multiproctoring/__init__.py", line 1, in <module>
    from .decorator import enable_npoed_multiproctoring
  File "/edx/app/edxapp/venvs/edxapp/src/npoed-multiproctoring/npoed_multiproctoring/decorator.py", line 4, in <module>
    from .models import CourseMultiproctoringState
  File "/edx/app/edxapp/venvs/edxapp/src/npoed-multiproctoring/npoed_multiproctoring/models.py", line 4, in <module>
    from openedx.core.djangoapps.xmodule_django.models import CourseKeyField
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/xmodule_django/models.py", line 10, in <module>
    from xmodule.modulestore.django import modulestore
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/modulestore/django.py", line 35, in <module>
    from xblock_django.user_service import DjangoXBlockUserService
  File "/edx/app/edxapp/edx-platform/common/djangoapps/xblock_django/user_service.py", line 4, in <module>
    from django.contrib.auth.models import User
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 247, in get_containing_app_config
    self.check_apps_ready()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/apps/registry.py", line 125, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
What's happen wrong?

**Comment by zimka** [comment]
Hi, unfortunately this app was tested with gingko release only, and porting it to the new release may be a bit tricky. I am not sure, but I think that this message means that current version of the app creates cyclic import, and this breaks django startup. Because we are still using gingko release, we are not working on porting app to hawthorn
